version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    tty: true

  app:
    build: app
    container_name: app
    restart: always
    tty: true
    depends_on:
      - db

  proxy:
    build: proxy
    container_name: proxy
    restart: always
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  mysql_data:
