version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    tty: true

volumes:
  mysql_data:
